### ISSUE TITLE
Migration to organization

### ISSUE THREAD

**Issue by Neustradamus** [CleanTalk/joomla3.x-4.x-antispam#25]
Dear @CleanTalk team,

It is possible to migrate the personal account to organization?

Converting:
- https://help.github.com/articles/converting-a-user-into-an-organization/

It is possible to rename this account and create the organization and move/transfer the repository to the organization.

Rename account:
- https://docs.github.com/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-user-account-settings/changing-your-github-username

Create an organization:
- https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/creating-a-new-organization-from-scratch

Transfer a repository:
- https://help.github.com/en/github/administering-a-repository/transferring-a-repository

Like:
- https://github.com/IBM
- http://github.com/gnome
- http://github.com/kde
- ...

**Comment by shagimuratov** [comment]
Hi @Neustradamus,

Thanks for the great suggestion!

If I understand right the biggest advantage for an organization is the ability to manage teams work. I don't think that we really need with feature right now. Am I missing something?

Please let me know your thoughts.

**Comment by Neustradamus** [comment]
Hello @shagimuratov,

Thanks for your answer.

The first step is that CleanTalk is not a person.

Thanks in advance.

**Comment by shagimuratov** [comment]
Got it. Please let me some time to figure out for the best way.

**Comment by shagimuratov** [comment]
Hi @Neustradamus, 

We moved the account to Organization status https://github.com/CleanTalk

Thank you for the participation.

**Comment by Neustradamus** [comment]
@shagimuratov: Good news, good job to @CleanTalk team!

**Comment by Neustradamus** [comment]
________________________________________
